### ISSUE TITLE
思源集市中并不是最新的 0.08 版本

### ISSUE THREAD

**Issue by denglinfu** [LinuaBio/GeogebraE#1]
非常感谢大佬的插件，日常使用非常顺手，但是近期发现思源集市中并不是最新的 0.08 版本，右键无法出现用 geogebra 打开

**Comment by denglinfu** [comment]
<img width="1241" alt="image" src="https://github.com/LinuaBio/GeogebraE/assets/144018470/f51cf3dc-f5d4-4dd0-8c37-6e77eb088ed1">

**Comment by Neurocylcq** [comment]
在修改了，有好久没有用思源了，最近才来继续开发，抱歉抱歉
